# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171204_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='users',
        ),
    ]
