# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='userifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=10)),
                ('weight', models.FloatField(max_length=10)),
                ('height', models.FloatField(max_length=10)),
                ('rank', models.IntegerField(max_length=10)),
                ('registerdata', models.DateField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='registerdata',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
