# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.rank'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='registerdata',
            field=models.DateTimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
