# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171210_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
