# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_testimgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimgsrc',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
