# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_testimgsrc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='iden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='iden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.iden'),
        ),
    ]
