# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_user_now_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_now',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.item'),
            preserve_default=False,
        ),
    ]
