# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_user_now_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeek3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
        migrations.CreateModel(
            name='week8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.item')),
            ],
        ),
    ]
