# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_weeek3_week1_week2_week4_week5_week6_week7_week8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weeek3',
            new_name='week3',
        ),
    ]
