# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180403_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(max_length=10),
        ),
    ]
