# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20180404_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_info',
            name='week0',
            field=models.FloatField(null=True),
        ),
    ]
