# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20180410_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_info',
            name='week1_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week2_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week3_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week4_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week5_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week6_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week7_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_info',
            name='week8_suggest',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
