# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20180410_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
